Update Algorithms.md
broadinstitute/consent-ontology pull request #790
Opened 2023-03-15 21:23 UTC by kaitlynoflaherty

## Addresses
https://broadworkbench.atlassian.net/jira/software/c/projects/DUOS/boards/123?modal=detail&selectedIssue=DUOS-1674

Updating Algorithm V3 documentation

----
Have you read [CONTRIBUTING.md](../CONTRIBUTING.md) lately? If not, do that first.

- Label PR with a Jira ticket number and include a link to the ticket
- Label PR with a security risk modifier [no, low, medium, high]
- PR describes scope of changes
- Get a minimum of one thumbs worth of review, preferably two if enough team members are available
- Get PO sign-off for all non-trivial UI or workflow changes
- Verify all tests go green
- Test this change deployed correctly and works on dev environment after deployment

2023-03-17 20:17 UTC, rushtong commented on docs/Algorithms.md
> +## Version 3
Let's add some UI enhancements here. We should have v1, v2 collapsed and v3 expanded. See https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections for how to do that.

Also, let's move v3 to the top, v2 next, then v1 last.

2023-03-21 19:04 UTC, fboulnois approved these changes
looks good, minor spacing nits:

2023-03-21 19:04 UTC, fboulnois commented on docs/Algorithms.md
> +## Version 3
```suggestion
## Version 3

```

2023-03-21 19:04 UTC, fboulnois commented on docs/Algorithms.md
> +<summary>View</summary>
```suggestion
<summary>View</summary>

```

2023-03-21 19:04 UTC, fboulnois commented on docs/Algorithms.md
> +Describes the involvement of studies that <strong>will not</strong> result in a decision from the DUOS algorithm.
```suggestion
Describes the involvement of studies that <strong>will not</strong> result in a decision from the DUOS algorithm.

```

2023-03-21 19:04 UTC, fboulnois commented on docs/Algorithms.md
>  ## Version 2
```suggestion
## Version 2

```

2023-03-21 19:04 UTC, fboulnois commented on docs/Algorithms.md
> +<summary>View</summary>
```suggestion
<summary>View</summary>

```

2023-03-21 19:04 UTC, fboulnois commented on docs/Algorithms.md
> +## Version 1
```suggestion
## Version 1

```

2023-03-21 19:04 UTC, fboulnois commented on docs/Algorithms.md
> +### Deprecated & Removed
```suggestion
### Deprecated & Removed

```

2023-03-22 11:00 UTC, rushtong requested changes

2023-03-22 11:00 UTC, rushtong commented on docs/Algorithms.md
> +          <li>Population Origins/Migration patterns (Answer is pre-determined based on selections made in Step 2)</li>
In this context, there is no form to reference
```suggestion
          <li>Population Origins/Migration patterns</li>
```

2023-03-22 11:00 UTC, rushtong commented on docs/Algorithms.md
> +			<th>If the DAR aims to involve...</th>
Here and throughout - in this context, we are describing a Research Purpose, not specifically a DAR. 
```suggestion
			<th>If the Research Purpose aims to involve...</th>
```

2023-03-22 11:00 UTC, rushtong commented on docs/Algorithms.md
> +        <li>No requirement in DAR or Algorithm</li>
The language here doesn't make sense to me. I think we can remove this altogether if there are no DUO terms to describe it.

2023-03-22 11:00 UTC, rushtong commented on docs/Algorithms.md
> +        <li>Assent in the DAR form</li>
Similar concern here - we should remove this bullet point

2023-03-22 11:00 UTC, rushtong commented on docs/Algorithms.md
> +        <li>Upload in the DAR form results in trigger a bypass of the algorithm</li>
Both cases here refer to something outside the scope of an algorithm discussion. I think we should remove them.

2023-03-22 11:00 UTC, rushtong commented on docs/Algorithms.md
> +Describes the involvement of studies that <strong>will not</strong> result in a decision from the DUOS algorithm.
After considering the abstention columns, I think we're adding more complexity and confusion with the second and third columns. I would suggest removing them altogether and adding some content here that explains a little more about why we are abstaining. Something along the lines of ...

> Due to the variety of sensitive research areas, ethical reasons, and areas where categorization is not possible, the DUOS system <strong>will not</strong> render a decision in the following cases.

2023-03-23 16:50 UTC, rushtong approved these changes
Thank you for the changes 👍🏽

2023-03-23 17:27 UTC, merged